// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
export type IconName =
  | '24Support'
  | '3Dcube'
  | '3DCubeScan'
  | '3DotsMore'
  | '3DRotate'
  | '3DSquare'
  | '3Square'
  | 'AaveAave'
  | 'Activity'
  | 'Add'
  | 'AddCircle'
  | 'AddItem'
  | 'AddSquare'
  | 'AiAc'
  | 'AiAdd'
  | 'AiAntenna'
  | 'AiCommentary'
  | 'AiFuelTank'
  | 'AiHeartSquare'
  | 'AiHomepage'
  | 'AiHospital'
  | 'AiHousing'
  | 'AiLandscape'
  | 'AiLoveletter'
  | 'Airdrop'
  | 'AiRecordVideo'
  | 'Airplane'
  | 'AirplaneSquare'
  | 'Airpod'
  | 'Airpods'
  | 'AiSandTimer'
  | 'AiSendMessage'
  | 'AiShapeTriangle'
  | 'AiSyringe'
  | 'AiTagPrice'
  | 'AiTools'
  | 'AiUsers'
  | 'AiWaterCycle'
  | 'AiWeight'
  | 'Alarm'
  | 'AlignBottom'
  | 'AlignHorizontally'
  | 'AlignLeft'
  | 'AlignLeft2'
  | 'AlignRight'
  | 'AlignTop'
  | 'AlignTop2'
  | 'AlignVertically'
  | 'Android'
  | 'Angel'
  | 'Angel2'
  | 'AnkrAnkr'
  | 'Apple'
  | 'Aquarius'
  | 'Archive'
  | 'Archive2'
  | 'Archive3'
  | 'ArchiveAdd'
  | 'ArchiveBook'
  | 'ArchiveMinus'
  | 'ArchiveSlash'
  | 'ArchiveTick'
  | 'Arrow'
  | 'ArrowBack'
  | 'ArrowCircleDown'
  | 'ArrowCircleLeft'
  | 'ArrowCircleRight'
  | 'ArrowCircleUp'
  | 'ArrowDown'
  | 'ArrowDown2'
  | 'ArrowDown3'
  | 'ArrowDown4'
  | 'ArrowForward'
  | 'ArrowLeft'
  | 'ArrowLeft2'
  | 'ArrowLeft3'
  | 'ArrowLeft42'
  | 'ArrowRight'
  | 'ArrowRight2'
  | 'ArrowRight3'
  | 'ArrowRight4'
  | 'ArrowSquare'
  | 'ArrowSquareDown'
  | 'ArrowSquareLeft'
  | 'ArrowSquareRight'
  | 'ArrowSquareUp'
  | 'ArrowSwap'
  | 'ArrowSwap2'
  | 'ArrowSwap3'
  | 'ArrowTransfer'
  | 'ArrowTransfer2'
  | 'ArrowUp'
  | 'ArrowUp2'
  | 'ArrowUp3'
  | 'ArrowUp4'
  | 'AttachCircle'
  | 'AttachSquare'
  | 'AudioSquare'
  | 'AugurRep'
  | 'Autobrightness'
  | 'AutonioNiox'
  | 'AvalancheAvax'
  | 'Award'
  | 'Backward'
  | 'Backward10Seconds'
  | 'Backward15Seconds'
  | 'Backward5Seconds'
  | 'BackwardItem'
  | 'Bag'
  | 'Bag2'
  | 'BagCross'
  | 'BagCross2'
  | 'BagHappy'
  | 'BagTick'
  | 'BagTick2'
  | 'BagTimer'
  | 'Ball'
  | 'Ball11'
  | 'Ball12'
  | 'Ball13'
  | 'Ball14'
  | 'Ball15'
  | 'Ball16'
  | 'Ball18'
  | 'Ball19'
  | 'Ball2'
  | 'Ball21'
  | 'Ball22'
  | 'Ball23'
  | 'Ball232'
  | 'Ball24'
  | 'Ball242'
  | 'Ball25'
  | 'Ball252'
  | 'Ball26'
  | 'Ball262'
  | 'Ball27'
  | 'Ball272'
  | 'Ball3'
  | 'Ball4'
  | 'Ball5'
  | 'Ball7'
  | 'Ball9'
  | 'Balll'
  | 'Baloons'
  | 'Bank'
  | 'Barcode'
  | 'Battery2Bars'
  | 'BatteryCharging'
  | 'BatteryDisable'
  | 'BatteryEmpty'
  | 'BatteryEmpty2'
  | 'BatteryFull'
  | 'Behance'
  | 'Bell'
  | 'Bell2'
  | 'Bezier'
  | 'Bill'
  | 'BinanceCoinBnb'
  | 'BinanceUsdBusd'
  | 'Birds'
  | 'BitcoinBtc'
  | 'BitcoinCard'
  | 'BitcoinConvert'
  | 'BitcoinRefresh'
  | 'Blend'
  | 'Blend2'
  | 'Blogger'
  | 'Bluetooth'
  | 'Bluetooth2'
  | 'BluetoothCircle'
  | 'BluetoothRectangle'
  | 'Blur'
  | 'Book'
  | 'BookingSnow'
  | 'Bookmark'
  | 'Bookmark2'
  | 'BookOpen'
  | 'BookSaved'
  | 'BookSquare'
  | 'Bootstrap'
  | 'Box'
  | 'Box2'
  | 'Box3'
  | 'BoxAdd'
  | 'BoxRemove'
  | 'BoxSearch'
  | 'BoxTick'
  | 'BoxTime'
  | 'Briefcase'
  | 'BrifecaseCross'
  | 'BrifecaseTick'
  | 'BrifecaseTimer'
  | 'Broom'
  | 'Brush'
  | 'BrushSquare'
  | 'Bubble'
  | 'Bucket'
  | 'BucketCircle'
  | 'BucketSquare'
  | 'Building'
  | 'Building2'
  | 'Building3'
  | 'Building4'
  | 'Buildings'
  | 'Buildings2'
  | 'Bus'
  | 'BuyCrypto'
  | 'Cake'
  | 'Cake2'
  | 'Cake3'
  | 'Calculator'
  | 'Calendar'
  | 'Calendar2'
  | 'Calendar3'
  | 'Calendar4'
  | 'Calendar5'
  | 'Calendar6'
  | 'CalendarAdd'
  | 'CalendarChristmas'
  | 'CalendarCircle'
  | 'CalendarDate'
  | 'CalendarEdit'
  | 'CalendarRemove'
  | 'CalendarSearch'
  | 'CalendarTick'
  | 'CalendarTree'
  | 'Call'
  | 'CallAdd'
  | 'CallCalling'
  | 'CallIncoming'
  | 'CallMinus'
  | 'CallOutgoing'
  | 'CallReceived'
  | 'CallRemove'
  | 'CallSlash'
  | 'Camera'
  | 'CameraSlash'
  | 'Candle'
  | 'Candle2'
  | 'Candy'
  | 'Candy2'
  | 'Candy3'
  | 'Candy4'
  | 'CandyCane'
  | 'CandyCane2'
  | 'CandyCane3'
  | 'CandyCane4'
  | 'Car'
  | 'Card'
  | 'CardAdd'
  | 'CardanoAda'
  | 'CardCoin'
  | 'CardEdit'
  | 'CardPos'
  | 'CardReceive'
  | 'CardRemove'
  | 'CardRemove2'
  | 'Cards'
  | 'CardSend'
  | 'CardSlash'
  | 'CardTick'
  | 'CardTick2'
  | 'Category'
  | 'Category2'
  | 'Cd'
  | 'CeloCelo'
  | 'CelsiusCel'
  | 'ChainlinkLink'
  | 'Chart'
  | 'Chart2'
  | 'Chart3'
  | 'Chart4'
  | 'ChartFail'
  | 'ChartSquare'
  | 'ChartSquare2'
  | 'ChartSuccess'
  | 'Chatbox'
  | 'Check'
  | 'ChristmasBell'
  | 'ChristmasBow'
  | 'ChristmasCard'
  | 'ChristmasHouse'
  | 'ChristmasShoes'
  | 'ChristmasSweater'
  | 'ChristmasTree'
  | 'ChristmasWreath'
  | 'Chrome'
  | 'CivicCvc'
  | 'Clipboard'
  | 'ClipboardClose'
  | 'ClipboardExport'
  | 'ClipboardImport'
  | 'ClipboardText'
  | 'ClipboardTick'
  | 'Clock'
  | 'Clock2'
  | 'Clock3'
  | 'Clock4'
  | 'CloseCircle'
  | 'CloseSquare'
  | 'Cloud'
  | 'CloudAdd'
  | 'CloudChange'
  | 'CloudConnection'
  | 'CloudCross'
  | 'CloudDrizzle'
  | 'CloudFog'
  | 'CloudLightning'
  | 'CloudMinus'
  | 'CloudNotif'
  | 'CloudPlus'
  | 'CloudRemove'
  | 'CloudSnow'
  | 'CloudSunny'
  | 'Code'
  | 'Code2'
  | 'CodeCircle'
  | 'Coffee'
  | 'Coin'
  | 'Coin2'
  | 'Colorfilter'
  | 'ColorsSquare'
  | 'ColorSwatch'
  | 'Command'
  | 'CommandSquare'
  | 'Component'
  | 'Computing'
  | 'ConversationBox'
  | 'Convert3DCube'
  | 'ConvertArrow'
  | 'ConvertCard'
  | 'Convertshape'
  | 'Convertshape2'
  | 'Copy'
  | 'Copyright'
  | 'CopySuccess'
  | 'Courthouse'
  | 'Cpu'
  | 'CpuCharge'
  | 'CpuSetting'
  | 'CreativeCommons'
  | 'Crop'
  | 'Crown'
  | 'Crown2'
  | 'Cup'
  | 'DaiDai'
  | 'Danger'
  | 'DashDash'
  | 'Data'
  | 'Data2'
  | 'Decor'
  | 'DecredDcr'
  | 'Deer'
  | 'DentDent'
  | 'Designtools'
  | 'DeviceMessage'
  | 'Devices'
  | 'Devices2'
  | 'Diagram'
  | 'Diamonds'
  | 'Direct'
  | 'DirectboxDefault'
  | 'DirectboxNotif'
  | 'DirectboxReceive'
  | 'DirectboxSend'
  | 'DirectDown'
  | 'DirectInbox'
  | 'DirectLeft'
  | 'DirectNormal'
  | 'DirectNotification'
  | 'DirectRight'
  | 'DirectSend'
  | 'DirectUp'
  | 'DiscountCircle'
  | 'DiscountShape'
  | 'Discover'
  | 'Discover2'
  | 'Dislike'
  | 'Document'
  | 'Document2'
  | 'DocumentCloud'
  | 'DocumentCode'
  | 'DocumentCode2'
  | 'DocumentCopy'
  | 'DocumentDownload'
  | 'DocumentFavorite'
  | 'DocumentFilter'
  | 'DocumentForward'
  | 'DocumentLike'
  | 'DocumentNormal'
  | 'DocumentPrevious'
  | 'DocumentSketch'
  | 'DocumentText'
  | 'DocumentText2'
  | 'DocumentUpload'
  | 'DollarCircle'
  | 'DollarSquare'
  | 'Dribbble'
  | 'Driver'
  | 'Driver2'
  | 'DriverRefresh'
  | 'Driving'
  | 'Drop'
  | 'Dropbox'
  | 'Edit'
  | 'Edit2'
  | 'EducareEkt'
  | 'Electricity'
  | 'EmailSnow'
  | 'EmercoinEmc'
  | 'EmojiHappy'
  | 'EmojiNormal'
  | 'EmojiSad'
  | 'EmptyWallet'
  | 'EmptyWalletAdd'
  | 'EmptyWalletChange'
  | 'EmptyWalletRemove'
  | 'EmptyWalletTick'
  | 'EmptyWalletTime'
  | 'EnhancePrize'
  | 'EnhanceUserAi'
  | 'EnjinCoinEnj'
  | 'EosEos'
  | 'Eraser'
  | 'Eraser2'
  | 'Ethereum'
  | 'EthereumClassicEtc'
  | 'ExportArrow'
  | 'ExportArrow2'
  | 'ExportCircle'
  | 'ExportCircle2'
  | 'ExternalDrive'
  | 'Eye'
  | 'EyeSlash'
  | 'Facebook'
  | 'FavoriteChart'
  | 'Figma'
  | 'FigmaCircle'
  | 'Filter'
  | 'FilterAdd'
  | 'FilterEdit'
  | 'FilterRemove'
  | 'FilterSearch'
  | 'FilterSquare'
  | 'FilterTick'
  | 'FingerCircle'
  | 'FingerScan'
  | 'Fire'
  | 'Fire2'
  | 'Fire3'
  | 'Fireworks'
  | 'Fireworks2'
  | 'Fireworks3'
  | 'Fireworks4'
  | 'Firstline'
  | 'Flag'
  | 'Flag2'
  | 'Flash'
  | 'Flash2'
  | 'FlashCircle'
  | 'FlashCircle2'
  | 'FlashSlash'
  | 'Folder'
  | 'Folder2'
  | 'FolderAdd'
  | 'FolderCloud'
  | 'FolderConnection'
  | 'FolderCross'
  | 'FolderFavorite'
  | 'FolderMinus'
  | 'FolderOpen'
  | 'Forbidden'
  | 'Forbidden2'
  | 'FormatCircle'
  | 'FormatSquare'
  | 'Forward'
  | 'Forward10Seconds'
  | 'Forward15Seconds'
  | 'Forward5Seconds'
  | 'ForwardItem'
  | 'Framer'
  | 'FtxTokenFtt'
  | 'Gallery'
  | 'GalleryAdd'
  | 'GalleryEdit'
  | 'GalleryExport'
  | 'GalleryFavorite'
  | 'GalleryImport'
  | 'GalleryRemove'
  | 'GallerySlash'
  | 'GalleryTick'
  | 'Game'
  | 'Gameboy'
  | 'GasStation'
  | 'Gemini'
  | 'Gemini2'
  | 'Ghost'
  | 'Gift'
  | 'Gift10'
  | 'Gift11'
  | 'Gift12'
  | 'Gift122'
  | 'Gift13'
  | 'Gift14'
  | 'Gift15'
  | 'Gift152'
  | 'Gift16'
  | 'Gift17'
  | 'Gift172'
  | 'Gift2'
  | 'Gift3'
  | 'Gift4'
  | 'Gift5'
  | 'Gift6'
  | 'Gift7'
  | 'Gift8'
  | 'Gift9'
  | 'GiftBag'
  | 'GiftCupcake'
  | 'Glass'
  | 'Glass2'
  | 'Glass3'
  | 'Global'
  | 'GlobalEdit'
  | 'GlobalRefresh'
  | 'GlobalSearch'
  | 'Google'
  | 'GoogleDrive'
  | 'GooglePlay'
  | 'Gps'
  | 'GpsSlash'
  | 'Graph'
  | 'Grid'
  | 'Grid2'
  | 'Grid3'
  | 'Grid4'
  | 'Grid5'
  | 'Grid6'
  | 'Grid7'
  | 'Grid8'
  | 'Grid9'
  | 'GridAdd'
  | 'GridEdit'
  | 'GridEqual'
  | 'GridEraser'
  | 'GridLock'
  | 'Grids'
  | 'HangingOrnament'
  | 'Happy'
  | 'Happyemoji'
  | 'HarmonyOne'
  | 'Hashtag'
  | 'Hashtag2'
  | 'HashtagDown'
  | 'HashtagUp'
  | 'Hat'
  | 'Hat2'
  | 'Hat3'
  | 'Headphone'
  | 'Headphones'
  | 'Health'
  | 'Heart'
  | 'HeartAdd'
  | 'HeartCircle'
  | 'HeartEdit'
  | 'HeartRemove'
  | 'HeartSearch'
  | 'HeartSlash'
  | 'HeartTick'
  | 'HederaHashgraphHbar'
  | 'HexHex'
  | 'Hierarchy'
  | 'Hierarchy2'
  | 'Hierarchy3'
  | 'HierarchySquare'
  | 'HierarchySquare2'
  | 'HierarchySquare3'
  | 'HolidayIcons'
  | 'Home'
  | 'Home2'
  | 'Home3'
  | 'HomeHashtag'
  | 'HomeTrendDown'
  | 'HomeTrendUp'
  | 'HomeWifi'
  | 'Horseshoe'
  | 'Hospital'
  | 'Hourglass'
  | 'House'
  | 'House2'
  | 'Html'
  | 'Html2'
  | 'HuobiTokenHt'
  | 'IconIcx'
  | 'Illustrator'
  | 'Image'
  | 'ImportArrow'
  | 'ImportArrow2'
  | 'ImportCircle'
  | 'ImportCircle2'
  | 'InfoCircle'
  | 'Information'
  | 'Instagram'
  | 'IostIost'
  | 'Javascript'
  | 'Js'
  | 'Judge'
  | 'Key'
  | 'Keyboard'
  | 'KeyboardOpen'
  | 'KeySquare'
  | 'KyberNetworkKnc'
  | 'Lamp'
  | 'Lamp2'
  | 'LampCharge'
  | 'LampChristmas'
  | 'LampOn'
  | 'LampSlash'
  | 'LanguageCircle'
  | 'LanguageSquare'
  | 'LanternStar'
  | 'Layer'
  | 'LayoutAdjust'
  | 'LeftBarGrid'
  | 'LeftSidebarGrid'
  | 'Level'
  | 'Lifebuoy'
  | 'Like'
  | 'Like2'
  | 'LikeDislike'
  | 'LikeShapes'
  | 'LikeTag'
  | 'Link'
  | 'Link2'
  | 'Link3'
  | 'Link4'
  | 'LinkCircle'
  | 'LinkSquare'
  | 'ListBullet'
  | 'ListNumber'
  | 'Litecoin'
  | 'Location'
  | 'LocationAdd'
  | 'LocationCross'
  | 'LocationMinus'
  | 'LocationSlash'
  | 'LocationTick'
  | 'Lock'
  | 'LockCircle'
  | 'LockSlash'
  | 'Login'
  | 'Login2'
  | 'Logout'
  | 'Logout2'
  | 'Lollipop'
  | 'Lovely'
  | 'Magic'
  | 'Magicpen'
  | 'MagicStar'
  | 'MagicWand'
  | 'MainComponent'
  | 'MakerMkr'
  | 'Man'
  | 'Map'
  | 'Map2'
  | 'Mask'
  | 'Mask2'
  | 'Mask3'
  | 'Math'
  | 'Maximize'
  | 'Maximize2'
  | 'Maximize3'
  | 'Maximize4'
  | 'Maximize5'
  | 'MaximizeCircle'
  | 'Medal'
  | 'MedalStar'
  | 'Menu'
  | 'Menu2'
  | 'MenuBoard'
  | 'MessageAdd'
  | 'MessageAdd2'
  | 'MessageBubble'
  | 'MessageCircle'
  | 'MessageEdit'
  | 'MessageFavorite'
  | 'MessageMinus'
  | 'MessageNotif'
  | 'MessageProgramming'
  | 'MessageQuestion'
  | 'MessageRemove'
  | 'Messages'
  | 'Messages2'
  | 'MessagesBubbles'
  | 'MessageSearch'
  | 'MessageSquare'
  | 'MessageText'
  | 'MessageText2'
  | 'MessageTick'
  | 'MessageTime'
  | 'Messenger'
  | 'Microphone'
  | 'Microphone2'
  | 'MicrophoneSlash'
  | 'MicrophoneSlash2'
  | 'Milk'
  | 'MiniMusicSquare'
  | 'Minus'
  | 'MinusCircle'
  | 'MinusSquare'
  | 'Mirror'
  | 'MirroringScreen'
  | 'Mistletoe'
  | 'Mitten'
  | 'Mobile'
  | 'MobileProgramming'
  | 'MoneroXmr'
  | 'Money'
  | 'Money2'
  | 'Money3'
  | 'Money4'
  | 'MoneyAdd'
  | 'MoneyChange'
  | 'MoneyForbidden'
  | 'MoneyRecive'
  | 'MoneyRemove'
  | 'Moneys'
  | 'MoneySend'
  | 'MoneyTick'
  | 'MoneyTime'
  | 'Monitor'
  | 'MonitorMobile'
  | 'MonitorRecorder'
  | 'Moon'
  | 'More'
  | 'MoreCircle'
  | 'MoreSquare'
  | 'Mouse'
  | 'Mouse2'
  | 'MouseCircle'
  | 'MouseSquare'
  | 'Music'
  | 'MusicalNoteAi'
  | 'MusicCircle'
  | 'MusicDashboard'
  | 'MusicFilter'
  | 'MusicLibrary'
  | 'Musicnote'
  | 'MusicPlay'
  | 'MusicPlaylist'
  | 'MusicSquare'
  | 'MusicSquareAdd'
  | 'MusicSquareRemove'
  | 'MusicSquareSearch'
  | 'NebulasNas'
  | 'NemXem'
  | 'NexoNexo'
  | 'Next'
  | 'Note'
  | 'Note2'
  | 'Note3'
  | 'Note4'
  | 'NoteAdd'
  | 'NoteFavorite'
  | 'NoteRemove'
  | 'NoteSquare'
  | 'NoteText'
  | 'Notification'
  | 'Notification2'
  | 'NotificationBing'
  | 'NotificationCircle'
  | 'NotificationFavorite'
  | 'NotificationStatus'
  | 'OceanProtocolOcean'
  | 'OkApp'
  | 'OkbOkb'
  | 'OmegaCircle'
  | 'OmegaSquare'
  | 'OntologyKnowledgeStructureConceptMapRelationshipDataModel'
  | 'Padlock'
  | 'PaintBrush'
  | 'PaintBrush2'
  | 'Paintbucket'
  | 'PaintRoller'
  | 'Paper'
  | 'Paper2'
  | 'Paperclip'
  | 'Paperclip2'
  | 'Paragraphspacing'
  | 'PartyHat'
  | 'PartyPopper'
  | 'PasswordCheck'
  | 'Path'
  | 'Path2'
  | 'PathSquare'
  | 'Pause'
  | 'PauseCircle'
  | 'Paypal'
  | 'PenAdd'
  | 'PenClose'
  | 'PenRemove'
  | 'PenTool'
  | 'PenTool2'
  | 'People'
  | 'PercentageCircle'
  | 'PercentageSquare'
  | 'Personalcard'
  | 'Pet'
  | 'Photoshop'
  | 'PictureFrame'
  | 'Play'
  | 'PlayAdd'
  | 'PlayCircle'
  | 'PlayCircle2'
  | 'PlayRemove'
  | 'PolkadotDot'
  | 'PolygonMatic'
  | 'PolyswarmNct'
  | 'PresentationChart'
  | 'Previous'
  | 'Printer'
  | 'PrinterSlash'
  | 'Profile'
  | 'Profile2User'
  | 'ProfileAdd'
  | 'ProfileCircle'
  | 'ProfileDelete'
  | 'ProfileRemove'
  | 'ProfileTick'
  | 'ProgrammingArrow'
  | 'ProgrammingArrows'
  | 'Python'
  | 'QuantQnt'
  | 'QuoteDown'
  | 'QuoteDownCircle'
  | 'QuoteDownSquare'
  | 'QuoteUp'
  | 'QuoteUpCircle'
  | 'QuoteUpSquare'
  | 'Radar'
  | 'Radar2'
  | 'Radar3'
  | 'Radio'
  | 'Ram'
  | 'Ram2'
  | 'Ranking'
  | 'Ranking2'
  | 'Ranking3'
  | 'Receipt'
  | 'Receipt2'
  | 'Receipt3'
  | 'Receipt4'
  | 'ReceiptAdd'
  | 'ReceiptDiscount'
  | 'ReceiptDisscount'
  | 'ReceiptEdit'
  | 'ReceiptItem'
  | 'ReceiptMinus'
  | 'ReceiptSearch'
  | 'ReceiptSquare'
  | 'ReceiptText'
  | 'Received'
  | 'ReceiveSquare'
  | 'ReceiveSquare2'
  | 'Record'
  | 'RecordCircle'
  | 'RecoveryConvert'
  | 'RedoArrow'
  | 'RefreshArrow'
  | 'RefreshArrow2'
  | 'RefreshCircle'
  | 'RefreshLeft'
  | 'RefreshRight'
  | 'RefreshSquare'
  | 'ReindeerAntlers'
  | 'ReindeerArch'
  | 'ReindeerFace'
  | 'RepeatArrow'
  | 'RepeatCircle'
  | 'RepeateMusic'
  | 'RepeateOne'
  | 'Reserve'
  | 'RotateLeft'
  | 'RotateLeft2'
  | 'RotateRight'
  | 'RotateRight2'
  | 'RouteSquare'
  | 'Routing'
  | 'Routing2'
  | 'RowHorizontal'
  | 'RowVertical'
  | 'Ruler'
  | 'RulerPen'
  | 'SafeHome'
  | 'Sagittarius'
  | 'Santa'
  | 'Santa2'
  | 'SantaHat'
  | 'SantaMouth'
  | 'Save'
  | 'SaveAdd'
  | 'SaveMinus'
  | 'SaveRemove'
  | 'Scan'
  | 'ScanBarcode'
  | 'Scanner'
  | 'Scanning'
  | 'Scissor'
  | 'Scissor2'
  | 'Screenmirroring'
  | 'Scroll'
  | 'Search'
  | 'SearchFavorite'
  | 'SearchFavorite2'
  | 'SearchNormal'
  | 'SearchStatus'
  | 'SearchStatus2'
  | 'SearchZoomIn'
  | 'SearchZoomIn2'
  | 'SearchZoomOut'
  | 'SearchZoomOut2'
  | 'Security'
  | 'SecurityCard'
  | 'SecuritySafe'
  | 'SecurityTime'
  | 'SecurityUser'
  | 'Send'
  | 'Send2'
  | 'Send3'
  | 'SendSquare'
  | 'SendSquare2'
  | 'ServingDome'
  | 'Setting'
  | 'Setting2'
  | 'Setting3'
  | 'Setting4'
  | 'Setting5'
  | 'Settings'
  | 'Shapes'
  | 'Shapes2'
  | 'Share'
  | 'Shield'
  | 'ShieldCross'
  | 'ShieldSearch'
  | 'ShieldSecurity'
  | 'ShieldSlash'
  | 'ShieldTick'
  | 'Ship'
  | 'Shop'
  | 'ShopAdd'
  | 'ShopGift'
  | 'ShoppingBag'
  | 'ShoppingCart'
  | 'ShopRemove'
  | 'ShopSnow'
  | 'Shuffle'
  | 'Shutterstock'
  | 'SiacoinSc'
  | 'SidebarBottom'
  | 'SidebarLeft'
  | 'SidebarRight'
  | 'SidebarTop'
  | 'Signpost'
  | 'Simcard'
  | 'Simcard2'
  | 'Simcard3'
  | 'Size'
  | 'Ski'
  | 'Slack'
  | 'Slash'
  | 'Sleigh'
  | 'Sleigh2'
  | 'Slider'
  | 'SliderHorizontal'
  | 'SliderHorizontal2'
  | 'SliderVertical'
  | 'SliderVertical2'
  | 'Smallcaps'
  | 'SmartBag'
  | 'SmartCar'
  | 'SmartCursor'
  | 'SmartHome'
  | 'SmartLockAi'
  | 'Smileys'
  | 'Sms'
  | 'SmsEdit'
  | 'SmsNotification'
  | 'SmsSearch'
  | 'SmsStar'
  | 'SmsTracking'
  | 'Snapchat'
  | 'Snow'
  | 'Snow10'
  | 'Snow102'
  | 'Snow11'
  | 'Snow12'
  | 'Snow13'
  | 'Snow14'
  | 'Snow2'
  | 'Snow3'
  | 'Snow4'
  | 'Snow5'
  | 'Snow6'
  | 'Snow7'
  | 'Snow8'
  | 'Snow9'
  | 'Snowflake'
  | 'Snowman'
  | 'Snowman2'
  | 'Snowman3'
  | 'Snowman4'
  | 'Snowman5'
  | 'Snowman6'
  | 'Snowman7'
  | 'Socks'
  | 'Socks2'
  | 'SolanaSol'
  | 'Sort'
  | 'Sound'
  | 'Sparkler'
  | 'Speaker'
  | 'Speedometer'
  | 'Spotify'
  | 'StacksStx'
  | 'Star'
  | 'Star2'
  | 'Star3'
  | 'Star4'
  | 'Star5'
  | 'Star6'
  | 'StarGarland'
  | 'Stars'
  | 'StarSlash'
  | 'Status'
  | 'StatusUp'
  | 'StellarXlm'
  | 'Stick'
  | 'Stick2'
  | 'Stick3'
  | 'Sticker'
  | 'Stickynote'
  | 'Stop'
  | 'StopCircle'
  | 'Story'
  | 'Strongbox'
  | 'Strongbox2'
  | 'Subtitle'
  | 'Sun'
  | 'SunFog'
  | 'SwapHorizontal'
  | 'SwapHorizontal2'
  | 'SwapHorizontal3'
  | 'Tag'
  | 'Tag2'
  | 'TagCross'
  | 'TagRight'
  | 'TagUser'
  | 'Task'
  | 'TaskSquare'
  | 'Teacher'
  | 'Telescope'
  | 'TenxPay'
  | 'TetherUsdt'
  | 'Text'
  | 'TextalignCenter'
  | 'TextalignJustifycenter'
  | 'TextalignJustifyleft'
  | 'TextalignJustifyright'
  | 'TextalignLeft'
  | 'TextalignRight'
  | 'TextBlock'
  | 'TextBold'
  | 'TextItalic'
  | 'TextUnderline'
  | 'TheGraphGrt'
  | 'ThetaTheta'
  | 'ThorchainRune'
  | 'TickCircle'
  | 'Ticket'
  | 'Ticket2'
  | 'TicketDiscount'
  | 'TicketExpired'
  | 'TicketStar'
  | 'TickSquare'
  | 'Timer'
  | 'TimerPause'
  | 'TimerStart'
  | 'ToggleOff'
  | 'ToggleOffCircle'
  | 'ToggleOn'
  | 'ToggleOnCircle'
  | 'TopBottomGrid'
  | 'Toy'
  | 'Toy2'
  | 'Toy3'
  | 'Toy4'
  | 'Toy5'
  | 'Toy6'
  | 'Trade'
  | 'TransactionMinus'
  | 'Translate'
  | 'Trash'
  | 'TrashSquare'
  | 'Tree'
  | 'Tree2'
  | 'Tree3'
  | 'Tree4'
  | 'Trello'
  | 'TrendDown'
  | 'TrendUp'
  | 'Triangle'
  | 'Triangle2'
  | 'TrontronTrx'
  | 'Truck'
  | 'TruckFast'
  | 'TruckRemove'
  | 'TruckTick'
  | 'TruckTime'
  | 'Twitch'
  | 'Ui8'
  | 'UndoArrow'
  | 'Unlimited'
  | 'Unlock'
  | 'UsdCoinUsdc'
  | 'User'
  | 'UserAdd'
  | 'UserCircleAdd'
  | 'UserEdit'
  | 'UserHexagon'
  | 'UserMinus'
  | 'UserRemove'
  | 'UserSearch'
  | 'UserSquare'
  | 'UserTag'
  | 'UserTick'
  | 'VelasVlx'
  | 'Verify'
  | 'VibeVibe'
  | 'Video'
  | 'VideoAdd'
  | 'VideoCircle'
  | 'VideoHorizontal'
  | 'VideoOctagon'
  | 'VideoPlay'
  | 'VideoRemove'
  | 'VideoSlash'
  | 'VideoSquare'
  | 'VideoTick'
  | 'VideoTime'
  | 'VideoVertical'
  | 'VoiceCircle'
  | 'VoiceSquare'
  | 'VolumeCross'
  | 'VolumeHigh'
  | 'VolumeLow'
  | 'VolumeLow2'
  | 'VolumeMute'
  | 'VolumeSlash'
  | 'VolumeUp'
  | 'Vuesax'
  | 'Wallet'
  | 'Wallet2'
  | 'Wallet3'
  | 'Wallet4'
  | 'WalletAdd'
  | 'WalletAdd2'
  | 'WalletCheck'
  | 'WalletMinus'
  | 'WalletMoney'
  | 'WalletRemove'
  | 'WalletSearch'
  | 'WanchainWan'
  | 'WanchainWan2'
  | 'Warning'
  | 'Watch'
  | 'WatchStatus'
  | 'Weight'
  | 'Weight2'
  | 'Whatsapp'
  | 'Wifi'
  | 'WifiSquare'
  | 'Wind'
  | 'Wind2'
  | 'Windows'
  | 'WingWing'
  | 'WinterBoots'
  | 'WinterMitten'
  | 'WinterPattern'
  | 'Woman'
  | 'Xd'
  | 'Xiaomi'
  | 'XrpXrp'
  | 'Youtube'
  | 'ZelZel'
  | 'Zipline'
  | 'Zoom'

export const ICON_NAMES = [
  '24Support',
  '3Dcube',
  '3DCubeScan',
  '3DotsMore',
  '3DRotate',
  '3DSquare',
  '3Square',
  'AaveAave',
  'Activity',
  'Add',
  'AddCircle',
  'AddItem',
  'AddSquare',
  'AiAc',
  'AiAdd',
  'AiAntenna',
  'AiCommentary',
  'AiFuelTank',
  'AiHeartSquare',
  'AiHomepage',
  'AiHospital',
  'AiHousing',
  'AiLandscape',
  'AiLoveletter',
  'Airdrop',
  'AiRecordVideo',
  'Airplane',
  'AirplaneSquare',
  'Airpod',
  'Airpods',
  'AiSandTimer',
  'AiSendMessage',
  'AiShapeTriangle',
  'AiSyringe',
  'AiTagPrice',
  'AiTools',
  'AiUsers',
  'AiWaterCycle',
  'AiWeight',
  'Alarm',
  'AlignBottom',
  'AlignHorizontally',
  'AlignLeft',
  'AlignLeft2',
  'AlignRight',
  'AlignTop',
  'AlignTop2',
  'AlignVertically',
  'Android',
  'Angel',
  'Angel2',
  'AnkrAnkr',
  'Apple',
  'Aquarius',
  'Archive',
  'Archive2',
  'Archive3',
  'ArchiveAdd',
  'ArchiveBook',
  'ArchiveMinus',
  'ArchiveSlash',
  'ArchiveTick',
  'Arrow',
  'ArrowBack',
  'ArrowCircleDown',
  'ArrowCircleLeft',
  'ArrowCircleRight',
  'ArrowCircleUp',
  'ArrowDown',
  'ArrowDown2',
  'ArrowDown3',
  'ArrowDown4',
  'ArrowForward',
  'ArrowLeft',
  'ArrowLeft2',
  'ArrowLeft3',
  'ArrowLeft42',
  'ArrowRight',
  'ArrowRight2',
  'ArrowRight3',
  'ArrowRight4',
  'ArrowSquare',
  'ArrowSquareDown',
  'ArrowSquareLeft',
  'ArrowSquareRight',
  'ArrowSquareUp',
  'ArrowSwap',
  'ArrowSwap2',
  'ArrowSwap3',
  'ArrowTransfer',
  'ArrowTransfer2',
  'ArrowUp',
  'ArrowUp2',
  'ArrowUp3',
  'ArrowUp4',
  'AttachCircle',
  'AttachSquare',
  'AudioSquare',
  'AugurRep',
  'Autobrightness',
  'AutonioNiox',
  'AvalancheAvax',
  'Award',
  'Backward',
  'Backward10Seconds',
  'Backward15Seconds',
  'Backward5Seconds',
  'BackwardItem',
  'Bag',
  'Bag2',
  'BagCross',
  'BagCross2',
  'BagHappy',
  'BagTick',
  'BagTick2',
  'BagTimer',
  'Ball',
  'Ball11',
  'Ball12',
  'Ball13',
  'Ball14',
  'Ball15',
  'Ball16',
  'Ball18',
  'Ball19',
  'Ball2',
  'Ball21',
  'Ball22',
  'Ball23',
  'Ball232',
  'Ball24',
  'Ball242',
  'Ball25',
  'Ball252',
  'Ball26',
  'Ball262',
  'Ball27',
  'Ball272',
  'Ball3',
  'Ball4',
  'Ball5',
  'Ball7',
  'Ball9',
  'Balll',
  'Baloons',
  'Bank',
  'Barcode',
  'Battery2Bars',
  'BatteryCharging',
  'BatteryDisable',
  'BatteryEmpty',
  'BatteryEmpty2',
  'BatteryFull',
  'Behance',
  'Bell',
  'Bell2',
  'Bezier',
  'Bill',
  'BinanceCoinBnb',
  'BinanceUsdBusd',
  'Birds',
  'BitcoinBtc',
  'BitcoinCard',
  'BitcoinConvert',
  'BitcoinRefresh',
  'Blend',
  'Blend2',
  'Blogger',
  'Bluetooth',
  'Bluetooth2',
  'BluetoothCircle',
  'BluetoothRectangle',
  'Blur',
  'Book',
  'BookingSnow',
  'Bookmark',
  'Bookmark2',
  'BookOpen',
  'BookSaved',
  'BookSquare',
  'Bootstrap',
  'Box',
  'Box2',
  'Box3',
  'BoxAdd',
  'BoxRemove',
  'BoxSearch',
  'BoxTick',
  'BoxTime',
  'Briefcase',
  'BrifecaseCross',
  'BrifecaseTick',
  'BrifecaseTimer',
  'Broom',
  'Brush',
  'BrushSquare',
  'Bubble',
  'Bucket',
  'BucketCircle',
  'BucketSquare',
  'Building',
  'Building2',
  'Building3',
  'Building4',
  'Buildings',
  'Buildings2',
  'Bus',
  'BuyCrypto',
  'Cake',
  'Cake2',
  'Cake3',
  'Calculator',
  'Calendar',
  'Calendar2',
  'Calendar3',
  'Calendar4',
  'Calendar5',
  'Calendar6',
  'CalendarAdd',
  'CalendarChristmas',
  'CalendarCircle',
  'CalendarDate',
  'CalendarEdit',
  'CalendarRemove',
  'CalendarSearch',
  'CalendarTick',
  'CalendarTree',
  'Call',
  'CallAdd',
  'CallCalling',
  'CallIncoming',
  'CallMinus',
  'CallOutgoing',
  'CallReceived',
  'CallRemove',
  'CallSlash',
  'Camera',
  'CameraSlash',
  'Candle',
  'Candle2',
  'Candy',
  'Candy2',
  'Candy3',
  'Candy4',
  'CandyCane',
  'CandyCane2',
  'CandyCane3',
  'CandyCane4',
  'Car',
  'Card',
  'CardAdd',
  'CardanoAda',
  'CardCoin',
  'CardEdit',
  'CardPos',
  'CardReceive',
  'CardRemove',
  'CardRemove2',
  'Cards',
  'CardSend',
  'CardSlash',
  'CardTick',
  'CardTick2',
  'Category',
  'Category2',
  'Cd',
  'CeloCelo',
  'CelsiusCel',
  'ChainlinkLink',
  'Chart',
  'Chart2',
  'Chart3',
  'Chart4',
  'ChartFail',
  'ChartSquare',
  'ChartSquare2',
  'ChartSuccess',
  'Chatbox',
  'Check',
  'ChristmasBell',
  'ChristmasBow',
  'ChristmasCard',
  'ChristmasHouse',
  'ChristmasShoes',
  'ChristmasSweater',
  'ChristmasTree',
  'ChristmasWreath',
  'Chrome',
  'CivicCvc',
  'Clipboard',
  'ClipboardClose',
  'ClipboardExport',
  'ClipboardImport',
  'ClipboardText',
  'ClipboardTick',
  'Clock',
  'Clock2',
  'Clock3',
  'Clock4',
  'CloseCircle',
  'CloseSquare',
  'Cloud',
  'CloudAdd',
  'CloudChange',
  'CloudConnection',
  'CloudCross',
  'CloudDrizzle',
  'CloudFog',
  'CloudLightning',
  'CloudMinus',
  'CloudNotif',
  'CloudPlus',
  'CloudRemove',
  'CloudSnow',
  'CloudSunny',
  'Code',
  'Code2',
  'CodeCircle',
  'Coffee',
  'Coin',
  'Coin2',
  'Colorfilter',
  'ColorsSquare',
  'ColorSwatch',
  'Command',
  'CommandSquare',
  'Component',
  'Computing',
  'ConversationBox',
  'Convert3DCube',
  'ConvertArrow',
  'ConvertCard',
  'Convertshape',
  'Convertshape2',
  'Copy',
  'Copyright',
  'CopySuccess',
  'Courthouse',
  'Cpu',
  'CpuCharge',
  'CpuSetting',
  'CreativeCommons',
  'Crop',
  'Crown',
  'Crown2',
  'Cup',
  'DaiDai',
  'Danger',
  'DashDash',
  'Data',
  'Data2',
  'Decor',
  'DecredDcr',
  'Deer',
  'DentDent',
  'Designtools',
  'DeviceMessage',
  'Devices',
  'Devices2',
  'Diagram',
  'Diamonds',
  'Direct',
  'DirectboxDefault',
  'DirectboxNotif',
  'DirectboxReceive',
  'DirectboxSend',
  'DirectDown',
  'DirectInbox',
  'DirectLeft',
  'DirectNormal',
  'DirectNotification',
  'DirectRight',
  'DirectSend',
  'DirectUp',
  'DiscountCircle',
  'DiscountShape',
  'Discover',
  'Discover2',
  'Dislike',
  'Document',
  'Document2',
  'DocumentCloud',
  'DocumentCode',
  'DocumentCode2',
  'DocumentCopy',
  'DocumentDownload',
  'DocumentFavorite',
  'DocumentFilter',
  'DocumentForward',
  'DocumentLike',
  'DocumentNormal',
  'DocumentPrevious',
  'DocumentSketch',
  'DocumentText',
  'DocumentText2',
  'DocumentUpload',
  'DollarCircle',
  'DollarSquare',
  'Dribbble',
  'Driver',
  'Driver2',
  'DriverRefresh',
  'Driving',
  'Drop',
  'Dropbox',
  'Edit',
  'Edit2',
  'EducareEkt',
  'Electricity',
  'EmailSnow',
  'EmercoinEmc',
  'EmojiHappy',
  'EmojiNormal',
  'EmojiSad',
  'EmptyWallet',
  'EmptyWalletAdd',
  'EmptyWalletChange',
  'EmptyWalletRemove',
  'EmptyWalletTick',
  'EmptyWalletTime',
  'EnhancePrize',
  'EnhanceUserAi',
  'EnjinCoinEnj',
  'EosEos',
  'Eraser',
  'Eraser2',
  'Ethereum',
  'EthereumClassicEtc',
  'ExportArrow',
  'ExportArrow2',
  'ExportCircle',
  'ExportCircle2',
  'ExternalDrive',
  'Eye',
  'EyeSlash',
  'Facebook',
  'FavoriteChart',
  'Figma',
  'FigmaCircle',
  'Filter',
  'FilterAdd',
  'FilterEdit',
  'FilterRemove',
  'FilterSearch',
  'FilterSquare',
  'FilterTick',
  'FingerCircle',
  'FingerScan',
  'Fire',
  'Fire2',
  'Fire3',
  'Fireworks',
  'Fireworks2',
  'Fireworks3',
  'Fireworks4',
  'Firstline',
  'Flag',
  'Flag2',
  'Flash',
  'Flash2',
  'FlashCircle',
  'FlashCircle2',
  'FlashSlash',
  'Folder',
  'Folder2',
  'FolderAdd',
  'FolderCloud',
  'FolderConnection',
  'FolderCross',
  'FolderFavorite',
  'FolderMinus',
  'FolderOpen',
  'Forbidden',
  'Forbidden2',
  'FormatCircle',
  'FormatSquare',
  'Forward',
  'Forward10Seconds',
  'Forward15Seconds',
  'Forward5Seconds',
  'ForwardItem',
  'Framer',
  'FtxTokenFtt',
  'Gallery',
  'GalleryAdd',
  'GalleryEdit',
  'GalleryExport',
  'GalleryFavorite',
  'GalleryImport',
  'GalleryRemove',
  'GallerySlash',
  'GalleryTick',
  'Game',
  'Gameboy',
  'GasStation',
  'Gemini',
  'Gemini2',
  'Ghost',
  'Gift',
  'Gift10',
  'Gift11',
  'Gift12',
  'Gift122',
  'Gift13',
  'Gift14',
  'Gift15',
  'Gift152',
  'Gift16',
  'Gift17',
  'Gift172',
  'Gift2',
  'Gift3',
  'Gift4',
  'Gift5',
  'Gift6',
  'Gift7',
  'Gift8',
  'Gift9',
  'GiftBag',
  'GiftCupcake',
  'Glass',
  'Glass2',
  'Glass3',
  'Global',
  'GlobalEdit',
  'GlobalRefresh',
  'GlobalSearch',
  'Google',
  'GoogleDrive',
  'GooglePlay',
  'Gps',
  'GpsSlash',
  'Graph',
  'Grid',
  'Grid2',
  'Grid3',
  'Grid4',
  'Grid5',
  'Grid6',
  'Grid7',
  'Grid8',
  'Grid9',
  'GridAdd',
  'GridEdit',
  'GridEqual',
  'GridEraser',
  'GridLock',
  'Grids',
  'HangingOrnament',
  'Happy',
  'Happyemoji',
  'HarmonyOne',
  'Hashtag',
  'Hashtag2',
  'HashtagDown',
  'HashtagUp',
  'Hat',
  'Hat2',
  'Hat3',
  'Headphone',
  'Headphones',
  'Health',
  'Heart',
  'HeartAdd',
  'HeartCircle',
  'HeartEdit',
  'HeartRemove',
  'HeartSearch',
  'HeartSlash',
  'HeartTick',
  'HederaHashgraphHbar',
  'HexHex',
  'Hierarchy',
  'Hierarchy2',
  'Hierarchy3',
  'HierarchySquare',
  'HierarchySquare2',
  'HierarchySquare3',
  'HolidayIcons',
  'Home',
  'Home2',
  'Home3',
  'HomeHashtag',
  'HomeTrendDown',
  'HomeTrendUp',
  'HomeWifi',
  'Horseshoe',
  'Hospital',
  'Hourglass',
  'House',
  'House2',
  'Html',
  'Html2',
  'HuobiTokenHt',
  'IconIcx',
  'Illustrator',
  'Image',
  'ImportArrow',
  'ImportArrow2',
  'ImportCircle',
  'ImportCircle2',
  'InfoCircle',
  'Information',
  'Instagram',
  'IostIost',
  'Javascript',
  'Js',
  'Judge',
  'Key',
  'Keyboard',
  'KeyboardOpen',
  'KeySquare',
  'KyberNetworkKnc',
  'Lamp',
  'Lamp2',
  'LampCharge',
  'LampChristmas',
  'LampOn',
  'LampSlash',
  'LanguageCircle',
  'LanguageSquare',
  'LanternStar',
  'Layer',
  'LayoutAdjust',
  'LeftBarGrid',
  'LeftSidebarGrid',
  'Level',
  'Lifebuoy',
  'Like',
  'Like2',
  'LikeDislike',
  'LikeShapes',
  'LikeTag',
  'Link',
  'Link2',
  'Link3',
  'Link4',
  'LinkCircle',
  'LinkSquare',
  'ListBullet',
  'ListNumber',
  'Litecoin',
  'Location',
  'LocationAdd',
  'LocationCross',
  'LocationMinus',
  'LocationSlash',
  'LocationTick',
  'Lock',
  'LockCircle',
  'LockSlash',
  'Login',
  'Login2',
  'Logout',
  'Logout2',
  'Lollipop',
  'Lovely',
  'Magic',
  'Magicpen',
  'MagicStar',
  'MagicWand',
  'MainComponent',
  'MakerMkr',
  'Man',
  'Map',
  'Map2',
  'Mask',
  'Mask2',
  'Mask3',
  'Math',
  'Maximize',
  'Maximize2',
  'Maximize3',
  'Maximize4',
  'Maximize5',
  'MaximizeCircle',
  'Medal',
  'MedalStar',
  'Menu',
  'Menu2',
  'MenuBoard',
  'MessageAdd',
  'MessageAdd2',
  'MessageBubble',
  'MessageCircle',
  'MessageEdit',
  'MessageFavorite',
  'MessageMinus',
  'MessageNotif',
  'MessageProgramming',
  'MessageQuestion',
  'MessageRemove',
  'Messages',
  'Messages2',
  'MessagesBubbles',
  'MessageSearch',
  'MessageSquare',
  'MessageText',
  'MessageText2',
  'MessageTick',
  'MessageTime',
  'Messenger',
  'Microphone',
  'Microphone2',
  'MicrophoneSlash',
  'MicrophoneSlash2',
  'Milk',
  'MiniMusicSquare',
  'Minus',
  'MinusCircle',
  'MinusSquare',
  'Mirror',
  'MirroringScreen',
  'Mistletoe',
  'Mitten',
  'Mobile',
  'MobileProgramming',
  'MoneroXmr',
  'Money',
  'Money2',
  'Money3',
  'Money4',
  'MoneyAdd',
  'MoneyChange',
  'MoneyForbidden',
  'MoneyRecive',
  'MoneyRemove',
  'Moneys',
  'MoneySend',
  'MoneyTick',
  'MoneyTime',
  'Monitor',
  'MonitorMobile',
  'MonitorRecorder',
  'Moon',
  'More',
  'MoreCircle',
  'MoreSquare',
  'Mouse',
  'Mouse2',
  'MouseCircle',
  'MouseSquare',
  'Music',
  'MusicalNoteAi',
  'MusicCircle',
  'MusicDashboard',
  'MusicFilter',
  'MusicLibrary',
  'Musicnote',
  'MusicPlay',
  'MusicPlaylist',
  'MusicSquare',
  'MusicSquareAdd',
  'MusicSquareRemove',
  'MusicSquareSearch',
  'NebulasNas',
  'NemXem',
  'NexoNexo',
  'Next',
  'Note',
  'Note2',
  'Note3',
  'Note4',
  'NoteAdd',
  'NoteFavorite',
  'NoteRemove',
  'NoteSquare',
  'NoteText',
  'Notification',
  'Notification2',
  'NotificationBing',
  'NotificationCircle',
  'NotificationFavorite',
  'NotificationStatus',
  'OceanProtocolOcean',
  'OkApp',
  'OkbOkb',
  'OmegaCircle',
  'OmegaSquare',
  'OntologyKnowledgeStructureConceptMapRelationshipDataModel',
  'Padlock',
  'PaintBrush',
  'PaintBrush2',
  'Paintbucket',
  'PaintRoller',
  'Paper',
  'Paper2',
  'Paperclip',
  'Paperclip2',
  'Paragraphspacing',
  'PartyHat',
  'PartyPopper',
  'PasswordCheck',
  'Path',
  'Path2',
  'PathSquare',
  'Pause',
  'PauseCircle',
  'Paypal',
  'PenAdd',
  'PenClose',
  'PenRemove',
  'PenTool',
  'PenTool2',
  'People',
  'PercentageCircle',
  'PercentageSquare',
  'Personalcard',
  'Pet',
  'Photoshop',
  'PictureFrame',
  'Play',
  'PlayAdd',
  'PlayCircle',
  'PlayCircle2',
  'PlayRemove',
  'PolkadotDot',
  'PolygonMatic',
  'PolyswarmNct',
  'PresentationChart',
  'Previous',
  'Printer',
  'PrinterSlash',
  'Profile',
  'Profile2User',
  'ProfileAdd',
  'ProfileCircle',
  'ProfileDelete',
  'ProfileRemove',
  'ProfileTick',
  'ProgrammingArrow',
  'ProgrammingArrows',
  'Python',
  'QuantQnt',
  'QuoteDown',
  'QuoteDownCircle',
  'QuoteDownSquare',
  'QuoteUp',
  'QuoteUpCircle',
  'QuoteUpSquare',
  'Radar',
  'Radar2',
  'Radar3',
  'Radio',
  'Ram',
  'Ram2',
  'Ranking',
  'Ranking2',
  'Ranking3',
  'Receipt',
  'Receipt2',
  'Receipt3',
  'Receipt4',
  'ReceiptAdd',
  'ReceiptDiscount',
  'ReceiptDisscount',
  'ReceiptEdit',
  'ReceiptItem',
  'ReceiptMinus',
  'ReceiptSearch',
  'ReceiptSquare',
  'ReceiptText',
  'Received',
  'ReceiveSquare',
  'ReceiveSquare2',
  'Record',
  'RecordCircle',
  'RecoveryConvert',
  'RedoArrow',
  'RefreshArrow',
  'RefreshArrow2',
  'RefreshCircle',
  'RefreshLeft',
  'RefreshRight',
  'RefreshSquare',
  'ReindeerAntlers',
  'ReindeerArch',
  'ReindeerFace',
  'RepeatArrow',
  'RepeatCircle',
  'RepeateMusic',
  'RepeateOne',
  'Reserve',
  'RotateLeft',
  'RotateLeft2',
  'RotateRight',
  'RotateRight2',
  'RouteSquare',
  'Routing',
  'Routing2',
  'RowHorizontal',
  'RowVertical',
  'Ruler',
  'RulerPen',
  'SafeHome',
  'Sagittarius',
  'Santa',
  'Santa2',
  'SantaHat',
  'SantaMouth',
  'Save',
  'SaveAdd',
  'SaveMinus',
  'SaveRemove',
  'Scan',
  'ScanBarcode',
  'Scanner',
  'Scanning',
  'Scissor',
  'Scissor2',
  'Screenmirroring',
  'Scroll',
  'Search',
  'SearchFavorite',
  'SearchFavorite2',
  'SearchNormal',
  'SearchStatus',
  'SearchStatus2',
  'SearchZoomIn',
  'SearchZoomIn2',
  'SearchZoomOut',
  'SearchZoomOut2',
  'Security',
  'SecurityCard',
  'SecuritySafe',
  'SecurityTime',
  'SecurityUser',
  'Send',
  'Send2',
  'Send3',
  'SendSquare',
  'SendSquare2',
  'ServingDome',
  'Setting',
  'Setting2',
  'Setting3',
  'Setting4',
  'Setting5',
  'Settings',
  'Shapes',
  'Shapes2',
  'Share',
  'Shield',
  'ShieldCross',
  'ShieldSearch',
  'ShieldSecurity',
  'ShieldSlash',
  'ShieldTick',
  'Ship',
  'Shop',
  'ShopAdd',
  'ShopGift',
  'ShoppingBag',
  'ShoppingCart',
  'ShopRemove',
  'ShopSnow',
  'Shuffle',
  'Shutterstock',
  'SiacoinSc',
  'SidebarBottom',
  'SidebarLeft',
  'SidebarRight',
  'SidebarTop',
  'Signpost',
  'Simcard',
  'Simcard2',
  'Simcard3',
  'Size',
  'Ski',
  'Slack',
  'Slash',
  'Sleigh',
  'Sleigh2',
  'Slider',
  'SliderHorizontal',
  'SliderHorizontal2',
  'SliderVertical',
  'SliderVertical2',
  'Smallcaps',
  'SmartBag',
  'SmartCar',
  'SmartCursor',
  'SmartHome',
  'SmartLockAi',
  'Smileys',
  'Sms',
  'SmsEdit',
  'SmsNotification',
  'SmsSearch',
  'SmsStar',
  'SmsTracking',
  'Snapchat',
  'Snow',
  'Snow10',
  'Snow102',
  'Snow11',
  'Snow12',
  'Snow13',
  'Snow14',
  'Snow2',
  'Snow3',
  'Snow4',
  'Snow5',
  'Snow6',
  'Snow7',
  'Snow8',
  'Snow9',
  'Snowflake',
  'Snowman',
  'Snowman2',
  'Snowman3',
  'Snowman4',
  'Snowman5',
  'Snowman6',
  'Snowman7',
  'Socks',
  'Socks2',
  'SolanaSol',
  'Sort',
  'Sound',
  'Sparkler',
  'Speaker',
  'Speedometer',
  'Spotify',
  'StacksStx',
  'Star',
  'Star2',
  'Star3',
  'Star4',
  'Star5',
  'Star6',
  'StarGarland',
  'Stars',
  'StarSlash',
  'Status',
  'StatusUp',
  'StellarXlm',
  'Stick',
  'Stick2',
  'Stick3',
  'Sticker',
  'Stickynote',
  'Stop',
  'StopCircle',
  'Story',
  'Strongbox',
  'Strongbox2',
  'Subtitle',
  'Sun',
  'SunFog',
  'SwapHorizontal',
  'SwapHorizontal2',
  'SwapHorizontal3',
  'Tag',
  'Tag2',
  'TagCross',
  'TagRight',
  'TagUser',
  'Task',
  'TaskSquare',
  'Teacher',
  'Telescope',
  'TenxPay',
  'TetherUsdt',
  'Text',
  'TextalignCenter',
  'TextalignJustifycenter',
  'TextalignJustifyleft',
  'TextalignJustifyright',
  'TextalignLeft',
  'TextalignRight',
  'TextBlock',
  'TextBold',
  'TextItalic',
  'TextUnderline',
  'TheGraphGrt',
  'ThetaTheta',
  'ThorchainRune',
  'TickCircle',
  'Ticket',
  'Ticket2',
  'TicketDiscount',
  'TicketExpired',
  'TicketStar',
  'TickSquare',
  'Timer',
  'TimerPause',
  'TimerStart',
  'ToggleOff',
  'ToggleOffCircle',
  'ToggleOn',
  'ToggleOnCircle',
  'TopBottomGrid',
  'Toy',
  'Toy2',
  'Toy3',
  'Toy4',
  'Toy5',
  'Toy6',
  'Trade',
  'TransactionMinus',
  'Translate',
  'Trash',
  'TrashSquare',
  'Tree',
  'Tree2',
  'Tree3',
  'Tree4',
  'Trello',
  'TrendDown',
  'TrendUp',
  'Triangle',
  'Triangle2',
  'TrontronTrx',
  'Truck',
  'TruckFast',
  'TruckRemove',
  'TruckTick',
  'TruckTime',
  'Twitch',
  'Ui8',
  'UndoArrow',
  'Unlimited',
  'Unlock',
  'UsdCoinUsdc',
  'User',
  'UserAdd',
  'UserCircleAdd',
  'UserEdit',
  'UserHexagon',
  'UserMinus',
  'UserRemove',
  'UserSearch',
  'UserSquare',
  'UserTag',
  'UserTick',
  'VelasVlx',
  'Verify',
  'VibeVibe',
  'Video',
  'VideoAdd',
  'VideoCircle',
  'VideoHorizontal',
  'VideoOctagon',
  'VideoPlay',
  'VideoRemove',
  'VideoSlash',
  'VideoSquare',
  'VideoTick',
  'VideoTime',
  'VideoVertical',
  'VoiceCircle',
  'VoiceSquare',
  'VolumeCross',
  'VolumeHigh',
  'VolumeLow',
  'VolumeLow2',
  'VolumeMute',
  'VolumeSlash',
  'VolumeUp',
  'Vuesax',
  'Wallet',
  'Wallet2',
  'Wallet3',
  'Wallet4',
  'WalletAdd',
  'WalletAdd2',
  'WalletCheck',
  'WalletMinus',
  'WalletMoney',
  'WalletRemove',
  'WalletSearch',
  'WanchainWan',
  'WanchainWan2',
  'Warning',
  'Watch',
  'WatchStatus',
  'Weight',
  'Weight2',
  'Whatsapp',
  'Wifi',
  'WifiSquare',
  'Wind',
  'Wind2',
  'Windows',
  'WingWing',
  'WinterBoots',
  'WinterMitten',
  'WinterPattern',
  'Woman',
  'Xd',
  'Xiaomi',
  'XrpXrp',
  'Youtube',
  'ZelZel',
  'Zipline',
  'Zoom',
] as const satisfies readonly IconName[]

export const ICON_COUNT = 1197
