// Generates the inline-icon registry (icons.ts) + IconName type (names.ts) from a
// raw Iconsax download. icons.ts is the committed source of truth that the <Icon>
// component reads — the raw .svg files are NOT kept in the repo.
//
// Workflow (icons change rarely):
//   1. Drop the raw Iconsax SVG dump into  icons-raw/  (gitignored).
//   2. Run  npm run build:icons
//   3. Commit the regenerated src/icons/icons.ts + src/icons/names.ts, clear icons-raw/.
//
// Cleaning: strips width/height (size is controlled by <Icon>), drops the no-op
// clipPath, and normalizes every color to `currentColor` so an <Icon> follows its
// CSS `color`.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const RAW_DIR = join(ROOT, 'icons-raw')
const OUT_DIR = join(ROOT, 'src/icons')
const HASH_RE = /-[0-9a-f]{12}-$/

/** filename -> clean kebab base (`iconsax-3-dots-more-<hash>-.svg` -> `3-dots-more`) */
const baseName = (file) =>
  file
    .replace(/\.svg$/i, '')
    .replace(/^iconsax-/, '')
    .replace(HASH_RE, '')

/** `3-dots-more` -> `3DotsMore` (uppercases the first letter of each dash-segment) */
const toPascal = (kebab) =>
  kebab
    .split('-')
    .map((s) => s.replace(/[a-z]/i, (c) => c.toUpperCase()))
    .join('')

/** `Clock2` -> `Clock3`, `Clock` -> `Clock2` — resolves name clashes deterministically */
const bump = (name) => {
  const m = name.match(/^(.*?)(\d+)$/)
  return m ? m[1] + (parseInt(m[2], 10) + 1) : name + '2'
}

/** Strip wrapper chrome and normalize colors. Returns inner markup for an icon. */
function processSvg(raw) {
  const strokeBased =
    (raw.match(/<svg[^>]*\bfill="([^"]+)"/i) || [, ''])[1].toLowerCase() === 'none'

  let inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/i, '') // drop opening <svg ...> (incl. width/height)
    .replace(/<\/svg>\s*$/i, '') // drop closing </svg>
    .replace(/<defs>[\s\S]*?<\/defs>/gi, '') // drop clipPath defs (no-op 24x24 rect)
    .replace(/\s*clip-path="[^"]*"/gi, '') // drop clip-path refs
    .replace(/#ffffff\b|#fff\b/gi, 'currentColor')
    .replace(/"white"/gi, '"currentColor"')

  // Stroke-based icons set fill="none" on the root, so bake fills explicitly: stroked shapes
  // stay unfilled, everything else takes currentColor — lets the wrapper use fill="currentColor".
  if (strokeBased) {
    inner = inner.replace(
      /<(path|circle|rect|ellipse|polygon|line|polyline)\b([^>]*?)(\/?)>/gi,
      (m, tag, attrs, slash) => {
        if (/\bfill=/i.test(attrs)) return m
        const add = /\bstroke=/i.test(attrs) ? ' fill="none"' : ' fill="currentColor"'
        return `<${tag}${attrs}${add}${slash ? '/' : ''}>`
      },
    )
  }

  return inner.replace(/>\s+</g, '><').trim()
}

if (!existsSync(RAW_DIR)) {
  console.error(`No raw icons found.\nDrop the Iconsax SVG dump into  ${RAW_DIR}/  and re-run.`)
  process.exit(1)
}

const rawFiles = readdirSync(RAW_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort()
if (rawFiles.length === 0) {
  // Guard: never overwrite the committed registry with an empty one.
  console.error(`${RAW_DIR}/ has no .svg files.\nDrop the Iconsax SVG dump there and re-run.`)
  process.exit(1)
}

const used = new Set()
const records = [] // { name, inner }

for (const file of rawFiles) {
  let name = toPascal(baseName(file))
  while (used.has(name)) name = bump(name) // resolve dup / native-numeric clashes
  used.add(name)
  records.push({ name, inner: processSvg(readFileSync(join(RAW_DIR, file), 'utf8')) })
}

records.sort((a, b) => a.name.localeCompare(b.name))

// icons.ts — name -> inner SVG markup (consumed by the <Icon> component).
writeFileSync(
  join(OUT_DIR, 'icons.ts'),
  `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.\n` +
    `import type { IconName } from './names'\n\n` +
    `export const icons: Record<IconName, string> = {\n` +
    records.map((r) => `  '${r.name}': ${JSON.stringify(r.inner)},`).join('\n') +
    `\n}\n`,
)

// names.ts — the IconName union + a runtime list.
const names = records.map((r) => r.name)
writeFileSync(
  join(OUT_DIR, 'names.ts'),
  `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.\n` +
    `export type IconName =\n${names.map((n) => `  | '${n}'`).join('\n')}\n\n` +
    `export const ICON_NAMES = [\n${names.map((n) => `  '${n}',`).join('\n')}\n] as const satisfies readonly IconName[]\n\n` +
    `export const ICON_COUNT = ${names.length}\n`,
)

console.log(`Processed ${records.length} icons -> src/icons/icons.ts, names.ts`)
